### ISSUE TITLE
run the tests

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-net-unix#13]
Actually the tests are built but are not run (because they need some tuntap magic). Would be great to add a way to run the tests automatically as well.

**Comment by mor1** [comment]
random thought: rather than requiring tuntap magic, i wonder if something could be constructed that used reads and writes to two files (eg., "netif1.pcap", "netif2.pcap"), and then compared them to a known (manually constructed?) test case? would also provide a natural way to backtrack and investigate any errors.

or, to put it another way, just how flexible and powerful are our functors? :)

**Comment by samoht** [comment]
that would be great indeed.

**Comment by avsm** [comment]
How about reading from a pcap file help test the mirage-net-unix functionality though?  This does nothing but read/write from tuntap...

**Comment by yomimono** [comment]
The tests are now run as of #30 .
