### ISSUE TITLE
Review the use of io-pages

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-net-unix#18]
Seems that io-pages are not necessary in unix-land (at least in that module). Maybe we should get rid of them here? Does only net-front and block-front need them?

/cc @avsm and @djs55

**Comment by avsm** [comment]
They're needed for block aligned I/O in Unix as well (eg with O_DIRECT).  What's the motivation for getting rid of them?

**Comment by hannesm** [comment]
as far as I can tell, io-page is not necessary in mirage-net-unix, so why keep such a dependency? It complicates the code occasionally (e.g. [in writev](https://github.com/mirage/mirage-net-unix/blob/master/lib/netif.ml#L169-L176) (could be replaced by a single line `Cstruct.concat pages`), which currently fails if more than 4096 bytes are transferred)...

I think it makes sense to distinguish between page-aligned memory and non-page-aligned memory in general in an OS, but since `NETWORK` in mirage-types moved towards `buffer` instead of `page_aligned_buffer`, I don't see a reason to clamp on `io-page` in here.

**Comment by avsm** [comment]
Fast user space networking (e.g. rump or netmap) will likely also introduce a page alignment restriction though.  Once you lose Io_page, you force a copy forever...

**Comment by djs55** [comment]
For reference the `Io_page` dependency starts in the signature: https://github.com/mirage/mirage-net/blob/master/lwt/mirage_net_lwt.ml

We would have to change it there and then change all implementations to match. As @avsm says we should investigate what's likely to happen with netmap before going too far. Or perhaps device some other way of expressing "this must be page aligned" in the interface? Perhaps some kind of memory allocator or page pool concept? It would be nice to be able to limit the memory usage of particular flows for example.

**Comment by hannesm** [comment]
my most recent design proposal in https://github.com/mirage/mirage-net/pull/13 addresses the concerns raised here imho: if we're going to implement netmap, its `allocate_frame` will allocate page-aligned memory :)

limiting memory usage of particular flows: should imho be done at a higher layer that knows about protocols (ethernet, ip) and flows (tcp)

**Comment by hannesm** [comment]
merged to master, will be part of 2.6.0 release.
