### ISSUE TITLE
MAC address used on TAP interface is always identical

### ISSUE THREAD

**Issue by mato** [mirage/mirage-net-unix#23]
Tested on several systems, mostly via https://github.com/mato/docker-unikernel-runner/tree/mirage-unix (but not docker-specific). The MAC address used by mirage-net-unix to communicate on the TAP interface is always identical:
````
Netif: plugging into tap0 with mac c2:9d:56:19:d7:2c
````
The MAC address is generated by the [code](https://github.com/mirage/mirage-net-unix/blob/master/lib/netif.ml#L72):
````
 let mac = Macaddr.make_local (fun _ -> Random.int 256) in
````
It looks like `Random` is not being seeded correctly -- what code should be responsible for this?

**Comment by hannesm** [comment]
likely noone calls `Random.self_init ()`.  It is called in https://github.com/mirage/mirage-tcpip/blob/25721d32f73eec66249316993773c387b587c658/tcp/pcb.ml#L648.

You can either call `Random.self_init ()` in mirage-net-unix, or have it somehow automatically be injected into startup (as done with nocrypto entropy initialisation)... in the long run, someone should reimplement the `Random` API on top of the nocrypto RNG (and use that all over, instead of the LFSR provided by Random)
